package logging

const S3_PATH_PARSE_ERROR = -10

const COULD_NOT_FIND_CREDENTIALS = -20

const PIPE_FAILURE = -30

const DB_SCHEMA_SCAN_FAILURE = -40
const DB_TRUNCATE_ERROR = -41

const DB_MISSING_TABLES = -50
